### ISSUE TITLE
Error: https://gsa.github.io/data/dotgov-domains/2014-12-01-full.csv

### ISSUE THREAD

**Issue by lboening** [GSA/data#10]
This does not return a file.

**Comment by konklone** [comment]
The issue is we have two repos using GitHub Pages competing for the same URL. :( So whenever one gets updated, it reclaims supremacy.

@gbinal Weren't you addressing this issue?

**Comment by lboening** [comment]
Perhaps I am doing it wrong? Is this feasible? Github doesn't really support links to static files, does it?

**Comment by gbinal** [comment]
Hi folks,  

This was my fault.  In setting up [open.gsa.gov](http://open.gsa.gov), I caused a conflict that resulted in this.  The actual conflict was over quickly but I needed to force a site rebuild to get this url working again.  This should now be done.  

@lboening - I'd say that Github does support links to static files.  It was my error that caused the interruption.

**Comment by gbinal** [comment]
To confirm - https://gsa.github.io/data/dotgov-domains/2014-12-01-full.csv is resolving.
