### ISSUE TITLE
How to inform you, or somebody, about the statuscode I get when I try to connect

### ISSUE THREAD

**Issue by lboening** [GSA/data#12]
I am testing the 5320 rows I received from the file https://gsa.github.io/data/dotgov-domains/2014-12-01-full.csv. I tried to connect to one out of forty. I connect to "http://" plus the domain name. I send a head request to each and look for a status code of 200 in return. I use simple Powershell script.

Of 134 attempts, 87 succeeded, 47 failed. Is this helpful at all? Out of curiosity, I am wondering what to think of this. Could your list be marked somehow with these facts?

**Comment by konklone** [comment]
So this is the list of registered domains -- they're definitely not all used. I recommend using a tool like @benbalter's [`site-inspector`](https://github.com/benbalter/site-inspector-ruby) to run over them and detect whether a site is live, simply a redirect, and what its canonical URL is.

I ran such a scan over the list earlier this month, to get a sense of HTTPS usage, and I've published this file in GitHub here:
https://github.com/GSA/https/blob/gh-pages/assets/data/scan-2014-02-06.csv

We'll publish more data like this over time, but ultimately these are all derivative datasets, that anyone can recreate with public tools. The fundamental official act that the .gov list represents is just making that list public, so derivative datasets like this can be made.

We have some more more work on scanning .gov domains here: https://github.com/18F/https-scan It's how we created the above spreadsheet, and how we'll be creating some others down the line.
