### ISSUE TITLE
Removing microsite: why?

### ISSUE THREAD

**Issue by lboening** [GSA/data#13]
Just curious to know why you mean by "removing microsite". I see the actions, of course.

Also, is the license changing?

**Comment by konklone** [comment]
It was mistakenly added here in https://github.com/GSA/data/commit/564a3061c2cdaf67501cacf19adaed3a3f870833, and the commit you refer to reverts it. We're moving at least the website portion over to https://github.com/GSA/open.gsa.gov.

@gbinal We should have LICENSE and CONTRIBUTING files here too, right?

**Comment by lboening** [comment]
I have to admit it can be confusing to know what I am in front of. Github does not make it all that easy.

**Comment by gbinal** [comment]
Sorry about that, @lboening.  @konklone is right - I was undoing an earlier integration of a separate project that is unrelated to the data in this repository.  

re: using GitHub, hang in there.  It'll start to make more sense but in the meantime, always feel free to ask questions here.  

re: Licensing - I've created https://github.com/GSA/data/issues/14.
