### ISSUE TITLE
create licensing/contributing files

### ISSUE THREAD

**Issue by gbinal** [GSA/data#14]
@konklone - I can add a CC-0 license file, but don't have any thoughts about a CONTRIBUTING file.  I see it as nice to have but not needed.

**Comment by kmsolimannitu** [comment]
"Hi there"
I am khan md soli man nitu.my father's name is engineer khan mohammod kamruzzaman.he love me very much.there is a repositor  JKZyou.he is cellect me CEO of JKZyou.I am so happy.I wish him/his friend.I also celeb rite all employ&sttaf.
Thank you father& other all.

**Comment by kmsolimannitu** [comment]
"JKZyou"
Www.github.com/kmkamruzzaman/JKZyou

"JKZyou.me"
is a web base company!
(a registared domain name)
www.facebook.com/JKZyou_is a company!it father's gif!

"JKZyou"
Native script
(alredi create a web site)

"JKZyou_is"

**Comment by kmsolimannitu** [comment]
Help someone to prosper in my"company" life.
You are invited for us!
JKZyou
CEO
Khan md soli man.nitu
(Monitor k zaman)

**Comment by kmsolimannitu** [comment]
"Www.github.com/kmkamruzzaman/JKZyou"

"www.face book.com/eng.kamruzzamanmale/JKZyou_is a company!"

"www.kmkamruzzamancom/JKZyou.statuspage.ion"

"www.kmkamruzzaman.word press.com/JKZyou"

**Comment by korovinsrg** [comment]
Москва
