### ISSUE TITLE
bcfp.gov

### ISSUE THREAD

**Issue by kelmej** [GSA/data#166]
why is it that GSA appears to own the domain but it is not secure? Is there some kind of malware attack or cookie? Sorry if this is misdirected, I am a new user of github but am curious about the https insecure warning I get when I try to navigate to bcfp.gov

**Comment by konklone** [comment]
@kelmej GSA just publishes the list of what .gov domains have been registered, and by which agencies. The Consumer Financial Protection Bureau owns bcfp.gov, and it redirects to consumerfinance.gov when accessed at https://bcfp.gov.

Accessing it at https://www.bcfp.gov does create a certificate error, and it looks like the CFPB has not configured their Akamai endpoints to present a custom domain certificate at that URL when `www` is used. That's an issue on CFPB's end, so you would need to contact them.
