### ISSUE TITLE
Rapid7 Open Data

### ISSUE THREAD

**Issue by hrbrmstr** [GSA/data#190]
Greetings!

I'm Rapid7 Labs' Chief Data Scientist and you can get _free_ FDNS data via https://opendata.rapid7.com/ (i.e. you can more regularly update the Rapid7-derived FDNS data set).

Just go to the site, hit one of the data boxes then use the signup form. The Labs team generally responds within 48hrs.

(hopefully the folks that monitor this GH aren't in the furloughed category)

-hrbrmstr

**Comment by IanLee1521** [comment]
Hi @hrbrmstr -- I'm not an admin on this repo, but I had pointed the efforts to the Rapid7 data in the past. Some of that is pulled in to https://github.com/GSA/data/tree/master/dotgov-websites (see bullet 2).

I like the idea of automating the pulling of the data from Rapid7, but there are some issues given the volume and needing such a small (.gov / .mil) slice of the domains.

**Comment by hrbrmstr** [comment]
It would be very straightforward for us to write a job that does a .gov / .mil export every time (~2wkd) the FDNS study runs and submit a PR to here with it if that sounds like something you'd be interested in.

**Comment by IanLee1521** [comment]
I'm not the owner of the repo, but I think something like a pull request to update https://github.com/GSA/data/blob/master/dotgov-websites/rdns-federal-snapshot.csv would be valuable, yes.

**Comment by h-m-f-t** [comment]
Hi @hrbrmstr. Super late response, but this post occurred during a government shutdown, and... somehow it is 6 months later.

Over at @cisagov, we'd be really interested in a pull of .gov hostnames seen in your scans if that's a thing you'd be interested in managing. Happy to chat here or at cameron.dixon@trio.dhs.gov.

**Comment by jsf9k** [comment]
@hrbrmstr I'm a colleague of @h-m-f-t's.  We would definitely use this data if it were submitted here, or to a repo in the @cisagov organization.

Submitting the data to a repo in the @cisagov organization would be better for us, since none of us have the authority to approve PRs and perform merges in GSA/data.  Thoughts, @h-m-f-t?
