### ISSUE TITLE
Unable to execute update.sh

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [GSA/data#239]
I followed the instructions on updating the IT Standards list but when I ran update.sh in my terminal in VSCode after cloning the repo -- nothing happened and I got the error message `zsh: no such file or directory: ./update.sh` . Not sure if I'm doing something wrong, or if it is because I don't have admin privileges or something changed on the backend.

**Comment by afeld** [comment]
Mmm, that sounds like you weren't executing from the `enterprise-architecture/` directory, so it couldn't find that script. Please reopen if I'm wrong!

**Comment by its-a-lisa-at-work** [comment]
thanks, I wasn't. Since the link in the OpsRotation checklist takes me directly there, it wasn't obvious that that was the directory I needed to be in based on the readme instructions
