### ISSUE TITLE
Data Package this data

### ISSUE THREAD

**Issue by rgrp** [GSA/data#25]
This means adding a datapackage.json which describes the data files. This will usually take <10m - and <5m if you know your JSON.

Instructions here: http://data.okfn.org/doc/publish-tabular#3-add-a-datapackage-json-file

Note given that you have a large variety of "cached query" style data - i.e. cuts of the main full csv you could just list the full csv in your datapackage.json if you wanted which would avoid adding all the other csvs.

**Why?**

Once you data package your data can be more easily accessed by a [variety of tools][tools] plus you can get a quick nice [automatic preview of your data using the viewer][viewer] - here's an [example](http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Frgrp%2Fcourt-decisions-gb).

[tools]: http://data.okfn.org/tools
[viewer]: http://data.okfn.org/tools/view

**Comment by konklone** [comment]
This repository is not the intended primary source for this data. The data should be published at https://catalog.data.gov/dataset/gov-domains-api-c9856. Right now it's just making it into this repo in a more timely fashion than it is being updated there.

**Comment by rgrp** [comment]
@konklone sure but no reason not to Data Package here too? I have a common pattern where I have data in github which i data package and gets pushed to ckan or other catalog.

**Comment by konklone** [comment]
I'd rather focus on getting to a place where we can close/redirect this repo entirely, personally. If others here feel differently, happy to do it.

**Comment by rgrp** [comment]
@konklone got you :-)
