### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by alexlitel** [GSA/data#30]
In the process of manually creating/maintaining a derivative dataset from the .gov domains CSV, I noticed a lot of errors w/r/t to classification and consistency. Please see the [attachment errors.txt](https://github.com/GSA/data/files/290366/errors.txt), and if there are any possible issues with accessing the file, I also [made a gist](https://gist.github.com/alexlitel/b015ebec3a99bc211d259c7886bc30d4) with the info.

P.S. I made [a small Angular app](http://alexlitel.github.io/dot-gov-domains) utilizing the .gov data that allows users to filter domains by name/agency/state and see the distribution of said domains.

**Comment by konklone** [comment]
Thank you so much for submitting these, @alexlitel! We are reviewing these for incorporation, and I'll leave this issue open while that's happening. We really appreciate your help at improving this foundational dataset.

**Comment by KevinO24** [comment]
The domain for Arlington Va is wrong. It gives you the Texas Arlington domain. i believe this is what your looking for.  https://www.arlingtonva.us/.
