### ISSUE TITLE
Missing domains from 2016-06-30 data

### ISSUE THREAD

**Issue by pzb** [GSA/data#34]
The latest data release is much closer to complete.  It seems that only a few domains are in DNS but not in the CSV file.  The ones with `test` in the name were in the FOIA response mentioned in the commit message, so it is not clear why they are not in this updated list, as it was released in the FOIA response.

``` text
ata.gov.
ecfc.gov.
erpo.gov.
gsatestfed.gov.
gsatestlocal.gov.
gsatestnsn.gov.
gsateststate.gov.
jpo.gov.
nrpo.gov.
owc.gov.
psd.gov.
psup.gov.
pubservices.gov.
rpo.gov.
testgsa2.gov.
vrsn-end-of-zone-marker-dummy-record.gov.
```

Could these get added to the next data update?

**Comment by konklone** [comment]
> vrsn-end-of-zone-marker-dummy-record.gov.

Is this domain actually in DNS?

**Comment by pzb** [comment]
Yes. https://github.com/pzb/TLDs/blob/master/gov/names/vrsn-end-of-zone-marker-dummy-record.gov. has the contents -- a TXT record with the value "plenus".

**Comment by konklone** [comment]
@pzb I think this dataset is now complete, and all of the still-registered domains you listed above are part of the dataset (except for the verisign dummy record).
