### ISSUE TITLE
needs LICENSE

### ISSUE THREAD

**Issue by afeld** [GSA/data#36]
We should add a LICENSE file to this repository...not sure what should be in there.

**Comment by A-gent** [comment]
Good plan.

**Comment by konklone** [comment]
From https://github.com/GSA/data/pull/45#issuecomment-257387588:

> We can't use a vanilla license, as the US government (we don't own copyright on our works). Also, the copyrightable status of data isn't the same as the copyrightable status of original works.
> 
> The data is produced by different offices in GSA, so I think for right now we need to leave it unlicensed. I'll add a note to the README pointing to [17 USC 105](https://www.law.cornell.edu/uscode/text/17/105) for now.

**Comment by guptasaloni** [comment]
can you please explain what is the main problem

**Comment by jayvdb** [comment]
Does https://github.com/GSA/data/commit/98f9268752 solve this issue?

**Comment by konklone** [comment]
I believe so.
