### ISSUE TITLE
NDCLOUD.GOV - State as "North Dakota" rather than ND

### ISSUE THREAD

**Issue by bmcguirk** [GSA/data#48]
Line 685 of [2016-09-09-state-local.csv](https://github.com/GSA/data/blob/gh-pages/dotgov-domains/2016-09-09-state-local.csv) has NDCLOUD.GOV 's State listed as "North Dakota" not "ND." Not even from North Dakota, just pointing it out.

**Comment by jasonrhaas** [comment]
This file no longer exists.  Should this issue be closed?

**Comment by afeld** [comment]
Looks like it's still the case in [`current-full.csv`](https://raw.githubusercontent.com/GSA/data/gh-pages/dotgov-domains/current-full.csv).

**Comment by smarina04** [comment]
fix is in the works.
