### ISSUE TITLE
Splitting dotgov data out into its own repo

### ISSUE THREAD

**Issue by konklone** [GSA/data#71]
I think the DotGov program will likely want to make its own repo, and push users there for feedback and discussion. Any objections from others using this repo?

cc @afeld

**Comment by afeld** [comment]
No objection from me, though I'd wait until that team exists in GSA before moving things around.

**Comment by gbinal** [comment]
All good with me.  My intention with this repo has always been for it to be an option for data publishers here until they found something that worked better for them.

**Comment by konklone** [comment]
@afeld At least as far as TTS goes, I am that team ;) But yeah, if we do it before it formally transfers, it'll be in close coordination with OGP.

**Comment by Aofzazgithub** [comment]
มันจะดีหรือ
