### ISSUE TITLE
GSA Schedule Data

### ISSUE THREAD

**Issue by mboone** [GSA/data#8]
Are there any APIs available (or in the works) that will simplify the download of GSA schedule data?  I was able to find data at http://www.gsaelibrary.gsa.gov/ElibMain/home.do but the site's construction makes download tedious as each schedule needs to be downloaded manually and the result is HTML (the link states Excel, but the file is HTML), not a delimited file that is machine readable without complicated parsing.

Any information would be greatly appreciated.

**Comment by ChrisWagner214** [comment]
@mboone Any updates on this?

**Comment by ChrisWagner214** [comment]
Does anyone from GSA even participate in these repos?  This is more than 18 months old and STILL open and unresponded to in this forum.

Adding to the question - SSQ data is even worse.  The reports available for SSQ have wither Contract with Schedule OR SIN, but not both.  Why does it need to be so hard to get this stuff in a form that can be used for reporting that can be joined to other sources.  For example, why can't we get current GSA Schedule data WITH SSQ data in one place, already joined together?

**Comment by nickvasilyev** [comment]
Elibrary lets you download schedule data in Excel. Here is an example:
https://www.gsaelibrary.gsa.gov/ElibMain/downloadInfo.do?source=BPA&fromPage=ss

Just click the Download button. You can do this for any of the schedules, by clicking "Download Contractors (Excel)"
