### ISSUE TITLE
Moved the main branch from gh-pages to master

### ISSUE THREAD

**Issue by konklone** [GSA/data#86]
This is just a notice to watchers: the main branch is now `master` instead of `gh-pages`. There is no longer a public permalink at a gsa.github.io URL.

**Comment by konklone** [comment]
It didn't occur to me until after I'd done this that some folks might be using github.com permalinks that reference `gh-pages` in the URL. I've restored a `gh-pages` branch from `master`, though `master` is still the default branch for now.

I'll re-open this if folks have any thoughts, but I think I'd like to get away from the commitment that there are gsa.github.io permalinks, and moving branches seems like the most reasonable way to do that.

**Comment by h-m-f-t** [comment]
The 🇺🇸  Department of Homeland Security thanks you for this heads up; we were indeed using gh-pages permalinks.

**Comment by konklone** [comment]
The General Services Administration was indeed using these as well...

**Comment by konklone** [comment]
@h-m-f-t Just to confirm, you were using `raw.githubusercontent.com` URLs, not `gsa.github.io` URLs, right?

**Comment by h-m-f-t** [comment]
@konklone, yes, that's correct.

**Comment by konklone** [comment]
@h-m-f-t You up for switching your permalinks to use `master` instead?

**Comment by h-m-f-t** [comment]
@konklone 👍  Crack that whip! Give the past the slip.

**Comment by pzb** [comment]
pulse.cio.gov has a link to https://github.com/GSA/data/tree/gh-pages/dotgov-domains

**Comment by WDTC399157852102002ZY9** [comment]
F51- : } f1 + f1 = 0.F2 centrid
